### ISSUE TITLE
meet error on app

### ISSUE THREAD

**Issue by schunlee** [vernu/textbee#12]
after I span App QR code, get error: Failed to obtain FCM token, my cellphone is HUAWEI SEA-AL10

**Comment by vernu** [comment]
@schunlee  TextBee relies on Google's Firebase Cloud Messaging (FCM) service. However, newer Huawei devices released after 2019 do not have access to Google services due to restrictions. So, Currently TextBee wont work on those recent Huawei devices that lack Google service support.
