### ISSUE TITLE
Fail to get FCM token

### ISSUE THREAD

**Issue by taozhiyuai** [vernu/textbee#13]
mobile is redmi m2012k10c

press update button, error info below the screen is "fail to get fcm token "

**Comment by kinboyw** [comment]
same problem, Huawei Mate60 Pro

**Comment by vernu** [comment]
@taozhiyuai @kinboyw 

TextBee relies on Google's Firebase Cloud Messaging service (FCM). However, newer Huawei devices released after 2019 do not have access to Google services due to restrictions. So, Currently TextBee wont work on those recent Chinese devices that lack Google service support.
