### ISSUE TITLE
App download is not working 

### ISSUE THREAD

**Issue by goldi0002** [vernu/textbee#14]

**Comment by vernu** [comment]
@goldi0002 what is not working? can u clarify?

**Comment by goldi0002** [comment]
You have mentioned a link to download from GitHub but that is not working

**Comment by vernu** [comment]
you can download the apk from [dl.textbee.dev](https://dl.textbee.dev) . If it doesn't work please try[https://github.com/vernu/textbee/releases/download/v2.3.1/TextBee.v2.3.1.apk](https://github.com/vernu/textbee/releases/download/v2.3.1/TextBee.v2.3.1.apk)

**Comment by goldi0002** [comment]
Thanks

**Comment by goldi0002** [comment]
One more things i want to know is this able to send MMS also textBee ?

**Comment by vernu** [comment]
> One more things i want to know is this able to send MMS also textBee ?

At the moment MMS is not supported, But it will be implemented in the future if there's a demand.
