### ISSUE TITLE
Missing "pages/api" directory

### ISSUE THREAD

**Issue by Reaperark** [vernu/textbee#16]
Hi Vernu, 
Directory "pages/api/" seems to be missing in "web" folder unless its changed and guide not updated. Thank you in advance. Great work.

**Comment by vernu** [comment]
@Reaperark the API is not in web folder its rather a standalone nestjs app located [here](https://github.com/vernu/textbee/tree/main/api)

**Comment by Reaperark** [comment]
Hi Vernu, thank you for your reply, i have managed to get it working. Great work.
