### ISSUE TITLE
URL REST FULL corriged

### ISSUE THREAD

**Issue by nemo93140** [vernu/textbee#2]
instead:
https://api.textbee.vernu.dev/api/v1/devices/${DEVICE_ID}/sendSMS?apiKey=${API_KEY}
replace with:
https://api.textbee.vernu.dev/api/v1/gateway/devices/${DEVICE_ID}/sendSMS?apiKey=${API_KEY}

**Comment by vernu** [comment]
Its been fixed now, thanks for ur contribution @nemo93140
