### ISSUE TITLE
[Enhancement] Adding interface to edit account informations

### ISSUE THREAD

**Issue by AlexandreIorio** [vernu/textbee#22]
First of all, congratulations on TextBee, it's an excellent piece of work! The application is intuitive and meets the needs perfectly.

However, I've noticed that there isn't an interface to edit account information when logged in via Gmail. I didn't try without Gmail. It would be useful to have the option to update personal details or manage account preferences.

Thank you in advance for considering this suggestion, and keep up the great work!

**Comment by vernu** [comment]
@AlexandreIorio, thanks for your feedback. Could you specify or list out what account information or preferences you'd like to be able to update from your dashboard?

**Comment by AlexandreIorio** [comment]
During my first connection I used google to authenticate myself, I would like to be able to have a standard account and remove google and put another email address. Is it possible?

**Comment by vernu** [comment]
> During my first connection I used google to authenticate myself, I would like to be able to have a standard account and remove google and put another email address. Is it possible?

currently you cant do that, I'll consider this feature in the future.
