### ISSUE TITLE
[Enhancement] Ability to Revoke API Key from Dashboard

### ISSUE THREAD

**Issue by AlexandreIorio** [vernu/textbee#23]
It would be great to have the option to revoke or disable an API key directly from the dashboard. This feature would enhance security by allowing users to manage their API keys more effectively, especially if a key has been compromised or is no longer needed.

Thanks in advance for considering this feature. Looking forward to seeing more great updates!

**Comment by vernu** [comment]
@AlexandreIorio I agree, that would be very helpful to manage compromized keys, i'll implement this feature in the coming releases,
thank you for the suggestion

**Comment by AlexandreIorio** [comment]
that will be fine, thank you. Is it possible to remove devices directly from the dashboard?

**Comment by vernu** [comment]
> that will be fine, thank you. Is it possible to remove devices directly from the dashboard?

At the moment, it’s not possible to remove devices directly from the dashboard. However, if you want, you can email me the device ID you want deleted, and I’ll take care of it for you. Just be sure to send the request from the email address you used to sign up.

**Comment by AlexandreIorio** [comment]
Thanks, I don't need to remove a device at the moment, but I'll be sure to contact you if I do.

**Comment by vernu** [comment]
@AlexandreIorio you can now revoke API keys as well as delete them from your dashboard
