### ISSUE TITLE
[Feature] Allow Webhook for Getting Message Replies

### ISSUE THREAD

**Issue by ilovefreesw** [vernu/textbee#6]
In app or web app, add an option to specify a webhook URL where the received messages will appear.

**Comment by vernu** [comment]
@ilovefreesw Do you mean a webhook for receiving incoming messages on a device?

**Comment by ilovefreesw** [comment]
No for redirecting incoming messages to a webhook so that a user can do whatever he wants with it. Just like what this app does: https://github.com/bogkonstantin/android_income_sms_gateway_webhook

It will be useful for many reasons.

**Comment by vernu** [comment]
> No for redirecting incoming messages to a webhook so that a user can do whatever he wants with it. Just like what this app does: https://github.com/bogkonstantin/android_income_sms_gateway_webhook
> 
> It will be useful for many reasons.

that sounds like a good feature, I'll definitely consider implementing it in the next releases.
Thank you.

**Comment by ilovefreesw** [comment]
And if you are looking for some paid opportunity to support this project, then you can create a paid app for GoHighLevel and charge like 10–50 dollars per month per account.

GoHighLevel is a SaaS for marketing agencies and this software is gowning like crazy. It has an SMS functionality via Twilio and their own SMS system. But you can build and publish a custom GHL Marketplace app(https://marketplace.gohighlevel.com/) by signing up for a free developer account. The app allows users to use their own Sim and phone to send SMS from the CRM. Register an OAuth app and then read their API(https://highlevel.stoplight.io/docs/integrations/0443d7d1a4bd0-overview) to create and manage conversation/messaging channels. It's very easy to implement.

**Comment by vernu** [comment]
> And if you are looking for some paid opportunity to support this project, then you can create a paid app for GoHighLevel and charge like 10–50 dollars per month per account.
> 
> GoHighLevel is a SaaS for marketing agencies and this software is gowning like crazy. It has an SMS functionality via Twilio and their own SMS system. But you can build and publish a custom GHL Marketplace app(https://marketplace.gohighlevel.com/) by signing up for a free developer account. The app will allow users to use their own Sim and phone to send SMS from the CRM. Register an OAuth app and then read their API(https://highlevel.stoplight.io/docs/integrations/0443d7d1a4bd0-overview) to create and manage conversation/messaging channels. It's very easy to implement.

sure, I'll check it out

**Comment by na7q** [comment]
I will second the webhook. This would be a game changer.

**Comment by parg0** [comment]
I am also seconding that webhook. Being able to receive and process SMS replies to someone you've already sent text message via textbee would be awesome!
Great app BTW! I don't use Patreon out of principle, but I would gladly send some money your way, via PayPal or by other means. Please do reach out.

**Comment by vernu** [comment]
webhook notification feature is live, closing this issue
