### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by amb26** [vernu/textbee#9]
After clicking through all the warnings about installing an app from an untrusted source, I just end up with "App not installed".
I am running Android 8.0.0 on a Galaxy S7

**Comment by leebufan** [comment]
me too.how can i install it?parse error when install it

**Comment by vernu** [comment]
@leebufan what's the android version are you using?

**Comment by x011** [comment]
What error do you get when you try to install the app via adb using `adb install app.apk`?

**Comment by nabildroid** [comment]
probably because playstore protection
